### ISSUE TITLE
Returning a component in a hook is a bad practice?

### ISSUE THREAD

**Issue by thepractice** [btholt/complete-intro-to-react-v5#62]
The useDropdown() hook returns the Dropdown component.

I think there is a performance concern here because each time useDropdown is called, we are returning a new component type. See https://www.reddit.com/r/reactjs/comments/9yq1l8/how_do_you_feel_about_a_hook_returning_components/.

Instead, we could use a regularly-defined Dropdown component here.

**Comment by 1Marc** [comment]
Yes, you're right. Brian is demoing the basic API of custom hooks based on what the core team was saying at the time. Best practices with custom hooks are still evolving since hooks are still only about a year old since they were announced. We'll adjust and adopt community best practices for custom hooks for the 2020 v6 version of the course! 😀
